### ISSUE TITLE
Run basic CAE on GPU

### ISSUE THREAD

**Issue by Serhiy-Shekhovtsov** [Serhiy-Shekhovtsov/mars-anomalies-aae#1]

**Comment by tsavchyn** [comment]
The very first run on GTX970, CUDA10, Ubuntu 18.04:
10 epochs on  - same result as on CPU, but significantly faster.

**Comment by Serhiy-Shekhovtsov** [comment]
@tsavchyn can you give an example of the running time?

**Comment by tsavchyn** [comment]
patch_size = 256
batch_size = 16
1 epoch:
`CPU times: user 21.6 s, sys: 9.08 s, total: 30.7 s
Wall time: 30.8 s`

**Comment by tsavchyn** [comment]
I am going to close this issue, since it works fine on GPUs.
